name: Fetch ALB Details

on:
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install AWS.Tools.ElasticLoadBalancingV2 module
        run: |
          Install-Module -Name AWS.Tools.Installer -Scope CurrentUser -Force
          Install-AWSToolsModule AWS.Tools.ElasticLoadBalancingV2 -Force -Scope CurrentUser
        shell: pwsh

      - name: Get ALB details
        run: |
          Import-Module AWS.Tools.ElasticLoadBalancingV2
          $albs = Get-ELBV2LoadBalancer
          Write-Output $albs
        shell: pwsh

