name: Fetch EC2 VPC Details

on:
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install AWS.Tools.EC2 and AWS.Tools.ElasticLoadBalancingV2 modules
        run: |
          Install-Module -Name AWS.Tools.EC2 -Force -Scope CurrentUser
          Install-Module -Name AWS.Tools.ElasticLoadBalancingV2 -Force -Scope CurrentUser
        shell: pwsh

      - name: Get EC2 VPC details
        run: |
          $vpcs = Get-EC2Vpc
          Write-Output $vpcs

          $ec2Instances = Get-EC2Instance
          Write-Output $ec2Instances

          $albs = Get-ELBV2LoadBalancer
          Write-Output $albs
        shell: pwsh
