name: "tf-workflow" 
on: 
  workflow_dispatch: 
jobs:    
  tfrun: 
    runs-on: ubuntu-latest
    name: "terraform run" 
    steps: 
      - name: checkout 
        uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
        env:
          NODE_VERSION: 20.x
        name: "Setup Terraform cli"    
        with:
            terraform_version: "1.7.4"

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform changes
        run: terraform plan

      - name: Apply Terraform changes
        run: terraform apply -auto-approve

      - name: Display EC2 Instance Details
        run: terraform output instance_details
