name: Fetch VPC Details

on:
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Get VPC details
        run: |
          aws ec2 describe-vpcs --query 'Vpcs[*].[VpcId, CidrBlock, InstanceTenancy, IsDefault, EnableDnsSupport, EnableDnsHostnames, DefaultNetworkAclId, DefaultSecurityGroup]' --output table
